# Generated by Django 3.2.6 on 2021-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=50)),
                ('st_name', models.CharField(max_length=255)),
                ('st_code', models.CharField(max_length=50)),
                ('st_buyprice', models.IntegerField()),
                ('st_targetprice', models.IntegerField()),
                ('st_stoploss', models.IntegerField()),
                ('st_ltp', models.IntegerField()),
                ('bought_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'bought_on',
            },
        ),
    ]
