# Generated by Django 3.2.6 on 2022-01-17 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertsmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_exchange_name', models.CharField(max_length=50)),
                ('al_type', models.CharField(max_length=50)),
                ('al_name', models.CharField(max_length=255)),
                ('al_code', models.CharField(max_length=50)),
                ('al_triggerprice', models.FloatField()),
                ('al_ltp', models.FloatField()),
                ('al_condition', models.CharField(max_length=255)),
                ('al_note', models.TextField()),
                ('al_user_id', models.IntegerField()),
                ('al_last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-al_last_updated',),
            },
        ),
        migrations.CreateModel(
            name='Stocksmain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(max_length=50)),
                ('st_type', models.CharField(max_length=50)),
                ('st_name', models.CharField(max_length=255)),
                ('st_code', models.CharField(max_length=50)),
                ('st_buyprice', models.FloatField()),
                ('st_targetprice', models.FloatField()),
                ('st_stoploss', models.FloatField()),
                ('st_ltp', models.FloatField()),
                ('bought_on', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-bought_on',),
            },
        ),
    ]
